### ISSUE TITLE
Background-repeat

### ISSUE THREAD

**Issue by arandamerinoalberto** [TheRandomCrew/TicTacToe-JS#15]
https://github.com/Israel-Laguan/TicTacToe-JS/blob/9e364a84be1f8036185a08785785756461e73c20/src/css/main.css#L39

Why use background-repeat: no-repeat; in this code line? Thanks

**Comment by Israel-Laguan** [comment]
If the image is smaller than the height, CSS tries to repeat the image automatically. By putting that rule this behavior is avoided.
