### ISSUE TITLE
 transform: scale(1.1);

### ISSUE THREAD

**Issue by arandamerinoalberto** [TheRandomCrew/TicTacToe-JS#16]
https://github.com/Israel-Laguan/TicTacToe-JS/blob/9e364a84be1f8036185a08785785756461e73c20/src/css/main.css#L54

What's its functionality?

**Comment by Israel-Laguan** [comment]
This tries to make the element a little bigger (a 10%, because is multiplied by 1.1). At the end, when hovered, the element is a little bit bigger.
