### ISSUE TITLE
const game = (() => {

### ISSUE THREAD

**Issue by arandamerinoalberto** [TheRandomCrew/TicTacToe-JS#17]
https://github.com/Israel-Laguan/TicTacToe-JS/blob/9e364a84be1f8036185a08785785756461e73c20/src/js/game.js#L2

I don't understand this code line. It's a empty variable ?

**Comment by Israel-Laguan** [comment]
It's a function that is automatically called when loaded, and goes by the name of IIFE. [Here](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) you have the official documentation. Notice the IIFE finish on line 129.
